"use client";

import { useEffect } from "react";
import { InvoicesTable } from "@/components/finance-dashboard/invoices-table";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { useFinanceStore } from "@/store/finance-store";
import { Loader2 } from "lucide-react";

export default function InvoicesPage() {
  const stats = useFinanceStore((s) => s.stats);
  const isLoading = useFinanceStore((s) => s.isLoading);
  const fetchStats = useFinanceStore((s) => s.fetchStats);
  const fetchInvoices = useFinanceStore((s) => s.fetchInvoices);

  useEffect(() => {
    fetchStats();
    fetchInvoices();
  }, [fetchStats, fetchInvoices]);

  const totalRevenue = stats.find((s) => s.title?.toLowerCase().includes("revenue"));
  const pendingStat = stats.find((s) => s.title?.toLowerCase().includes("pending"));
  const overdueStat = stats.find((s) => s.title?.toLowerCase().includes("overdue"));

  return (
    <div className="p-6 space-y-6">
      <div className="flex flex-col gap-2">
        <h1 className="text-3xl font-bold tracking-tight">Invoices</h1>
        <p className="text-muted-foreground">
          Create, manage, and track invoices for customers and partners.
        </p>
      </div>

      <div className="grid gap-4 md:grid-cols-3">
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Total Revenue (Month)</CardTitle>
          </CardHeader>
          <CardContent>
            {isLoading ? (
              <Loader2 className="h-5 w-5 animate-spin text-muted-foreground" />
            ) : (
              <>
                <div className="text-2xl font-bold">{totalRevenue?.value ?? "₦0"}</div>
                <p className="text-xs text-muted-foreground">
                  {totalRevenue?.change ?? ""} {totalRevenue?.description ?? ""}
                </p>
              </>
            )}
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Pending Invoices</CardTitle>
          </CardHeader>
          <CardContent>
            {isLoading ? (
              <Loader2 className="h-5 w-5 animate-spin text-muted-foreground" />
            ) : (
              <>
                <div className="text-2xl font-bold">{pendingStat?.value ?? "0"}</div>
                <p className="text-xs text-muted-foreground">
                  {pendingStat?.change ?? ""} {pendingStat?.description ?? ""}
                </p>
              </>
            )}
          </CardContent>
        </Card>
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Overdue</CardTitle>
          </CardHeader>
          <CardContent>
            {isLoading ? (
              <Loader2 className="h-5 w-5 animate-spin text-muted-foreground" />
            ) : (
              <>
                <div className="text-2xl font-bold text-red-600">{overdueStat?.value ?? "0"}</div>
                <p className="text-xs text-muted-foreground">
                  {overdueStat?.change ?? ""} {overdueStat?.description ?? ""}
                </p>
              </>
            )}
          </CardContent>
        </Card>
      </div>

      <Card>
        <CardHeader>
          <CardTitle>All Invoices</CardTitle>
          <CardDescription>
            A list of all invoices generated by the system.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <InvoicesTable />
        </CardContent>
      </Card>
    </div>
  );
}
